//generateReadme populating ReadME document
function generateReadme(answers) {
  return `
  <h1 align="center">${answers.title}</h1>

  ![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)<br />

## Description
${answers.description}

## Table of Contents
* [Description](#description)
* [Install](#install)
* [Usage](#usage)
* [License](#license)
* [Contribution](#contribution)
* [Test](#test)
* [Questions](#questions)

## Install
${answers.install}

## Usage
${answers.usage}

## License
![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)
<br />
This application is covered by the ${answers.license} license.

## Contribution
${answers.contribution}

## Test
${answers.test}

## Questions
${answers.questions}<br />
<br />
Find me on Github: [${answers.Github}](https://github.com/${answers.Github})
Email me with any questions: ${answers.email} <br />

This README was generated by [ReadME-Generator](https://github.com/awchen85/README-Generator)
`;
}
module.exports = generateReadme;
